name: Report an issue with Immich
description: Report an issue with Immich
body:
  - type: checkboxes
    attributes:
      label: I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.
      options:
        - label: 'Yes'

  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!

        If you have a feature or enhancement request, please use the [feature request][fr] section of our [GitHub Discussions][fr].

        [fr]: https://github.com/immich-app/immich/discussions/new?category=feature-request

  - type: textarea
    validations:
      required: true
    attributes:
      label: The bug
      description: >-
        Describe the issue you are experiencing here, to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
