blank_issues_enabled: false
contact_links:
  - name: I have a question or need support
    url: https://discord.gg/D8JsnBEuKb
    about: We use GitHub for tracking bugs, please check out our Discord channel for freaky fast support.
  - name: Feature Request
    url: https://github.com/bo0tzz/github-playground/discussions/new?category=feature-request
    about: Please use our GitHub Discussion for making feature requests.
