on:
  workflow_dispatch:

name: foo

jobs:
  success-check:
    runs-on: ubuntu-latest
    steps:
      - uses: immich-app/devtools/actions/success-check@81113db03f6d743efee81e0058c0b43f6cd6f36d # v0.0.6
        with:
          needs: ""
