on:
  issues: 
    types: [opened]
  discussion: 
    types: [created]

jobs:
  get_body:
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ toJSON(github.event) }}
    outputs:
      body: ${{ steps.get_body.outputs.body }}
    steps:
      - id: get_body
        run: |
          BODY=$(echo $EVENT | jq '.issue // .discussion | .body' | base64 -w 0)
          echo "body=$BODY" >> $GITHUB_OUTPUT
  
  get_checkbox_json:
    runs-on: ubuntu-latest
    needs: get_body
    container:
      image: yshavit/mdq:0.7.2
    outputs:
      json: ${{ steps.get_checkbox.outputs.json }}
    steps:
      - id: get_checkbox
        env:
          BODY: ${{ needs.get_body.outputs.body }}
        run: |
          JSON=$(echo "$BODY" | base64 -d | /mdq --output json '# I have searched | - [?] Yes')
          echo "json=$JSON" >> $GITHUB_OUTPUT

  post_comment:
    runs-on: ubuntu-latest
    needs: get_checkbox_json
    if: ${{ !fromJSON(needs.get_checkbox_json.outputs.json).items[0].list[0].checked }}
    steps:
      - run: echo 'bad'
