on:
  issues: 
    types: [opened, reopened]
  discussion: 
    types: [created]

jobs:
  get_checkbox_json:
    runs-on: ubuntu-latest
    container:
      image: yshavit/mdq:0.7.2
    outputs:
      json: ${{ steps.get_checkbox.outputs.json }}
    steps:
      - id: get_checkbox
        env:
          BODY: ${{ github.event.*.body }}
        run: |
          JSON=$(echo "$BODY" | /mdq --output json '# I have searched | - [?] Yes')
          echo "json=$JSON" >> $GITHUB_OUTPUT

  post_comment:
    runs-on: ubuntu-latest
    needs: get_checkbox_json
    if: ${{ !fromJSON(needs.get_checkbox_json.outputs.json).items[0].list[0].checked }}
    steps:
      - run: echo 'bad'
