name: Test permissions
on:
  push:
permissions: {}
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello > world.txt
      - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
        with:
          name: hello-world
          path: world.txt
