on:
  workflow_dispatch:
  workflow_call:
    inputs:
      skip:
        required: false
        type: boolean

jobs:
  fail:
    runs-on: ubuntu-latest
    if: ${{ inputs.skip != true }}
    outputs:
      foo: ${{ steps.step.outputs.out }}
    steps:
      - id: step
        run: |
          x=2
          y=7
          echo "out=($x,$y)" >> $GITHUB_OUTPUT
          exit 1

  mid:
    runs-on: ubuntu-latest
    if: ${{ inputs.skip != true }}
    needs: fail
    steps:
      - run: |
          cat <<EOF
          ${{ toJson(needs) }}
          EOF

  finish:
    runs-on: ubuntu-latest
    needs: mid
    steps:
      - run: echo 'done'
