on:
  workflow_dispatch:
  workflow_call:
    inputs:
      skip:
        required: false
        type: boolean

jobs:
  fail:
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.step.outputs.out }}
    steps:
      - id: step
        if: ${{ inputs.skip != true }}
        run: |
          x=2
          y=7
          echo "out=($x,$y)" >> $GITHUB_OUTPUT
          exit 1

      - if: ${{ inputs.skip != true }}
        run: |
          cat <<EOF
          ${{ toJson(steps.step) }}
          EOF
      
      - run: echo 'done'
