on:
  workflow_dispatch:

jobs:
  matrixed:
    runs-on: ubuntu-latest
    outputs:
      val: ${{ steps.step.outputs.val }}
    strategy:
      matrix:
        x: [1, 2, 3]
        y: [4, 5, 6]
    steps:
      - id: step
        run: echo "val=(${{ matrix.x }},${{ matrix.y}})" >> $GITHUB_OUTPUT

  finish:
    runs-on: ubuntu-latest
    needs: matrixed
    steps:
      - run: |
          cat <<EOF
          ${{ toJson(needs) }}
          EOF
