on:
  workflow_dispatch:

jobs:
  matrixed:
    runs-on: ubuntu-latest
    outputs:
      ${{ matrix.id }}: ${{ steps.step.outputs.out }}
    strategy:
      matrix:
        include:
          - id: 4
            x: 1
            y: 4
          - id: 18
            x: 3
            y: 6
          - id: 8
            x: 2
            y: 4
    steps:
      - id: step
        run: |
          x=${{ matrix.x }}
          y=${{ matrix.y }}
          echo "out=($x,$y)" >> $GITHUB_OUTPUT

  finish:
    runs-on: ubuntu-latest
    needs: matrixed
    steps:
      - run: |
          cat <<EOF
          ${{ toJson(needs) }}
          EOF
