on:
  workflow_dispatch:

jobs:
  fail:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      foo: ${{ steps.step.outputs.out }}
    steps:
      - id: step
        run: |
          x=2
          y=7
          echo "out=($x,$y)" >> $GITHUB_OUTPUT
          exit 1

  finish:
    runs-on: ubuntu-latest
    needs: fail
    steps:
      - run: |
          cat <<EOF
          ${{ toJson(needs) }}
          EOF
