on:
  push:
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      
      - name: mdq
        uses: docker://ghcr.io/immich-app/mdq:main@sha256:476bd00d0b41a95cd799b6feff86ca221d795a1576e7d691e4fbe1c476a9767d
        with:
          entrypoint: /bin/sh
          args: -c "/mdq '#' README.md --output json | jq '.items[0].section.title' -r"

      - run: echo ${{ toJSON(steps) }}
